#!/bin/sh

# -----------------------------------
# Project   : Khmer_word_recognition
# Author    : Chanmann Lim
#
# Changelogs:
#   - 02/10/2016  : file created.
# -----------------------------------

# exit on error
set -e

# E_VARS
E_USAGE="Usage: $0 (ubuntu | mac | restore)"

# global variables
SCRIPT_NAME=$0
OS=
BACKUP="port.backup"

# show usage
show_usage() {
  echo $E_USAGE >&2
}

# port_ubuntu
port_ubuntu() {
  echo "$SCRIPT_NAME -> port_ubuntu"
  echo
  
  mkdir "$BACKUP"
  ls *.sh | while read file; do
    mv $file "$BACKUP/$file"
    sed "s/sort -u/sort -uV/g" "$BACKUP/$file" > $file
    chmod a+x $file
  done
}

# port_mac
port_mac() {
  echo "$SCRIPT_NAME -> port_mac"
  echo
  
  mkdir "$BACKUP"
  ls *.sh | while read file; do
    mv $file "$BACKUP/$file"
    sed "s/sort -uV/sort -u/g" "$BACKUP/$file" > $file
    chmod a+x $file
  done
}

# restore
restore() {
  echo "$SCRIPT_NAME -> restore"
  echo
  
  if [ -d "$BACKUP" ]; then
    mv $BACKUP/*.sh ./
    rm -r $BACKUP
  fi
}

# main
main() {
  bash ./args_check.sh 1 $@ || (show_usage && exit 1)
  OS=$1
  case ${OS} in
    "ubuntu" ) port_ubuntu;;
    "mac"    ) port_mac;;
    "restore") restore_port;;
    *        ) show_usage
  esac
}

# ------------------------------------
# make_connect_hed.sh - make connect.hed for DNN-HMM initialization
#
#   $1 : (ubuntu | mac)
# ------------------------------------

  main $@
  